---
title: "multivariate-model"
output: 
    html_document:
        number_sections: true
        toc: true
        float_toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = FALSE)
```

# Loading data, setting up 

```{r}
library(tidyverse)
library(lme4)
library(brms)
library(sjstats)
library(tidybayes)
library(gt)

d1 <- read_csv("imuscle-esm.csv")
d2 <- read_csv("scimo-esm.csv")
d3 <- read_csv("stemie-esm.csv")
```

```{r}
# STEM-IE

d3 <- d3 %>%
    mutate(program_ID = paste0(program_ID, " ", sociedad_class)) %>%
    mutate(program_ID = str_replace(program_ID, " NA", ""))

# Overall

d1s <- d1 %>% dplyr::mutate(participant_ID = STUDID,
                            program_ID = str_c(d1$TEACHID, " - ", d1$PERIOD)) %>%
    select(participant_ID,
           beep_ID,
           program_ID,
           aff_enga,
           beh_enga,
           cog_enga) %>%
    mutate(dataset = "imuscle",
           participant_ID = as.character(participant_ID),
           program_ID = as.character(program_ID))

d2s <- d2 %>%
    select(participant_ID = stud_ID,
           program_ID = teacher_ID,
           beep_ID,
           aff_enga,
           beh_enga,
           cog_enga) %>%
    mutate(dataset = "scimo",
           program_ID = as.character(program_ID))

subtact_one <- function(x) x - 1

d3s <- d3 %>%
    mutate(program_ID = paste0(program_ID, " ", sociedad_class)) %>%
    mutate(program_ID = str_replace(program_ID, " NA", "")) %>%
    select(beep_ID = beep_ID_new,
           cog_enga = cognitive_engagement,
           beh_enga = behavioral_engagement,
           aff_enga = affective_engagement,
           participant_ID,
           program_ID) %>%
    mutate(dataset = "stemie") %>%
    mutate(participant_ID = as.character(participant_ID)) %>%
    mutate_at(vars(contains("enga")), subtact_one)

dd <- bind_rows(d1s, d2s, d3s)

dd <- dd %>%
    group_by(participant_ID, program_ID, beep_ID) %>%
    gather(key, val, -participant_ID, -beep_ID, -program_ID, -dataset) %>%
    summarize(mean_enga = mean(val, na.rm = TRUE)) %>%
    right_join(dd)

dd
```

# Desc

```{r}
dd %>%
    select(aff_enga, beh_enga, cog_enga) %>% 
    apaTables::apa.cor.table(filename = "cor-table.doc")
```

# Model

```{r, eval = FALSE}
mood <- brm(mvbind(aff_enga, beh_enga, cog_enga) ~ -1 +
                (1| a | participant_ID) + (1| b | beep_ID) + (1| c | program_ID) +
                dataset,
            data = dd,
            iter = 4000, chains = 4,
            cores = 4)

write_rds(mood, "final-model.rds")
```

```{r}
mood <- read_rds("final-model.rds")

mood
```

# Summary table

```{r}
# mood <- `final-model`

d1 <- summary(mood)$fixed
d2 <- summary(mood)$random
d2a <- d2$beep_ID
d2b <- d2$participant_ID
d2c <- d2$program_ID
d3 <- summary(mood)$spec_pars
d4 <- summary(mood)$rescor_pars

d <- rbind(d1, d2a, d2b, d2c, d3, d4) %>% 
    as.data.frame() %>% 
    rownames_to_column("Var") %>% 
    as_tibble() %>% 
    select(Var, Estimate, Est_Error = Est.Error, Lower_CI = `l-95% CI`, Upper_CI = `u-95% CI`)

t <- d %>% 
    mutate(category = c(rep("Response-Dataset Intercept", 9),
                        rep("Situation Var", 3),
                        rep("Individual Var", 3),
                        rep("Program Var", 3),
                        rep("Ranef Corr.", 9), 
                        rep("Residual", 3),
                        rep("Residual Corr.", 3))) %>% 
    group_by(category) %>% 
    gt::gt() %>% 
    gt::fmt_number(columns = vars(Estimate, Est_Error, Lower_CI, Upper_CI)) %>% 
    gt::tab_row_group()

t

t %>% 
    fmt_number(vars(Estimate, Est_Error, Lower_CI, Upper_CI)) %>% 
    gt::gtsave("esm-icc-estimates.rtf")
```

```{r}

# var component by outcome
re_p <- function(p) {
    p <- ifelse(p > .999, "p < .001",
                ifelse(p > .95, str_c("p = ", round(1-p, 3)),
                       ifelse(p < .001, "p < .001",
                              ifelse(p < .05, str_c("p = ", round(p, 3)), p))))
    p
}

## RQ2
hypothesis(mood, 
           c("sd_beep_ID__affenga_Intercept>sd_participant_ID__affenga_Intercept", 
             "sd_participant_ID__affenga_Intercept>sd_program_ID__affenga_Intercept",
             "sd_beep_ID__affenga_Intercept>sd_program_ID__affenga_Intercept",
             "sd_beep_ID__behenga_Intercept>sd_participant_ID__behenga_Intercept", 
             "sd_participant_ID__behenga_Intercept>sd_program_ID__behenga_Intercept",
             "sd_beep_ID__behenga_Intercept>sd_program_ID__behenga_Intercept",
             "sd_beep_ID__cogenga_Intercept>sd_participant_ID__cogenga_Intercept", 
             "sd_participant_ID__cogenga_Intercept>sd_program_ID__cogenga_Intercept",
             "sd_beep_ID__cogenga_Intercept>sd_program_ID__cogenga_Intercept"),
           class = NULL) %>% 
    pluck(1) %>% 
    mutate(Estimate = str_c(round(abs(Estimate), 3), " (", round(Est.Error,3), "), ", re_p(Post.Prob))) 

## RQ2
hypothesis(mood, 
           c("sd_beep_ID__affenga_Intercept>sd_beep_ID__behenga_Intercept", 
             "sd_beep_ID__behenga_Intercept>sd_beep_ID__cogenga_Intercept",
             "sd_beep_ID__affenga_Intercept>sd_beep_ID__cogenga_Intercept",
             "sd_participant_ID__affenga_Intercept>sd_participant_ID__behenga_Intercept", 
             "sd_participant_ID__behenga_Intercept>sd_participant_ID__cogenga_Intercept",
             "sd_participant_ID__affenga_Intercept>sd_participant_ID__cogenga_Intercept",
             "sd_program_ID__affenga_Intercept>sd_program_ID__behenga_Intercept", 
             "sd_program_ID__behenga_Intercept>sd_program_ID__cogenga_Intercept",
             "sd_program_ID__affenga_Intercept>sd_program_ID__cogenga_Intercept"),
           class = NULL) %>% pluck(1) %>% 
    mutate(Estimate = str_c(round(abs(Estimate), 3), " (", round(Est.Error,3), "), ", re_p(Post.Prob))) %>% 
    select(Estimate) %>% 
    clipr::write_clip()

# Dataset

hypothesis(mood, 
           c("b_affenga_datasetstemie>b_affenga_datasetscimo", 
             "b_affenga_datasetstemie>b_affenga_datasetimuscle",
             "b_affenga_datasetscimo>b_affenga_datasetimuscle",
             "b_behenga_datasetstemie>b_behenga_datasetscimo", 
             "b_behenga_datasetstemie>b_behenga_datasetimuscle",
             "b_behenga_datasetscimo>b_behenga_datasetimuscle",
             "b_cogenga_datasetstemie>b_cogenga_datasetscimo", 
             "b_cogenga_datasetstemie>b_cogenga_datasetimuscle",
             "b_cogenga_datasetscimo>b_cogenga_datasetimuscle"),
           class = NULL) %>% 
    pluck(1) %>% 
    mutate(Estimate = str_c(round(abs(Estimate), 3), " (", round(Est.Error,3), "), ", re_p(Post.Prob))) %>% 
    select(Estimate) %>% 
    clipr::write_clip()

## res correlations

## at program level
hypothesis(mood, 
           c("cor_program_ID__affenga_Intercept__behenga_Intercept>cor_program_ID__affenga_Intercept__cogenga_Intercept", 
             "cor_program_ID__affenga_Intercept__behenga_Intercept>cor_program_ID__behenga_Intercept__cogenga_Intercept",
             
             "cor_participant_ID__affenga_Intercept__behenga_Intercept>cor_participant_ID__affenga_Intercept__cogenga_Intercept", 
             "cor_participant_ID__affenga_Intercept__behenga_Intercept>cor_participant_ID__behenga_Intercept__cogenga_Intercept",
             
             "cor_beep_ID__affenga_Intercept__behenga_Intercept>cor_beep_ID__affenga_Intercept__cogenga_Intercept", 
             "cor_beep_ID__affenga_Intercept__behenga_Intercept>cor_beep_ID__behenga_Intercept__cogenga_Intercept",
             
             "rescor__affenga__behenga>rescor__affenga__cogenga",
             "rescor__affenga__behenga>rescor__behenga__cogenga"),
           class = NULL) %>% 
    pluck(1) %>% 
    mutate(Estimate = str_c(round(abs(Estimate), 3), " (", round(Est.Error,3), "), ", re_p(Post.Prob))) %>% 
    select(Estimate) %>% 
    clipr::write_clip()

## aff and cog, at different levels
hypothesis(mood, 
           c("cor_participant_ID__affenga_Intercept__cogenga_Intercept=cor_beep_ID__affenga_Intercept__cogenga_Intercept",
             "cor_participant_ID__affenga_Intercept__cogenga_Intercept=cor_program_ID__affenga_Intercept__cogenga_Intercept",
             "cor_program_ID__affenga_Intercept__cogenga_Intercept=cor_beep_ID__affenga_Intercept__cogenga_Intercept"),
           class = NULL)
```

```{r}
tibble::tribble(
        ~Outcome, ~Hypothesis, ~`Diff`,
     "Affective",           "Sit. - Ind.",      "0.257 (0.017), p < .001",
     "Affective",          "Sit. - Prog.",      "0.348 (0.034), p < .001",
     "Affective",          "Sit. - Prog.",     "0.091 (0.032), p = 0.004",
    "Behavioral",           "Sit. - Ind.",       "0.31 (0.016), p < .001",
    "Behavioral",          "Sit. - Prog.",      "0.397 (0.029), p < .001",
    "Behavioral",          "Sit. - Prog.",     "0.088 (0.028), p = 0.001",
     "Cognitive",           "Sit. - Ind.",      "0.494 (0.018), p < .001",
     "Cognitive",          "Sit. - Prog.",      "0.451 (0.037), p < .001",
     "Cognitive",          "Sit. - Prog.",         "0.043 (0.033), 0.089"
    ) %>% 
    mutate(hypothesis = str_c(Outcome, ": ", Hypothesis)) %>% 
    select(hypothesis, Diff) %>%
    mutate()
    spread(hyp)

```

# Plot 
# AFF 

```{r}

x <- VarCorr(mood)

xx <- rbind(x$beep_ID$sd, x$participant_ID$sd,x$program_ID$sd,x$residual__$sd) %>% 
    as_tibble() %>% 
    mutate(var = c(rep("beep", 3), rep("ind", 3), rep("prog", 3), rep("resid", 3)),
           out = rep(c("aff", "beh", "cog"), 4))

xx$Variance <- xx$Estimate ^ 2
xx$Est.Error <- xx$Est.Error ^ 2

tot_var <- xx %>% 
    group_by(out) %>% 
    summarize(total_var = sum(Variance))

# aff
resid <- mood %>% 
    spread_draws(sigma_affenga) %>% 
    mutate(est = sigma_affenga ^ 2) %>% 
    mutate(var = "residual") %>% 
    select(-.chain, -sigma_affenga) %>% 
    mutate(ICC = est /tot_var$total_var[1])
beeps <- mood%>%
    spread_draws(r_beep_ID__affenga[condition, term]) %>% 
    group_by(.chain, .iteration) %>% 
    summarize(r_beep_ID = var(r_beep_ID__affenga)) %>% 
    ungroup() %>% 
    mutate(ICC = r_beep_ID/tot_var$total_var[1]) %>% 
    mutate(var = 'situation') %>% 
    rename(est = r_beep_ID)
peeps <- mood %>%
    spread_draws(r_participant_ID__affenga[condition, term]) %>% 
    group_by(.chain, .iteration) %>% 
    summarize(r_participant_ID = var(r_participant_ID__affenga)) %>% 
    ungroup() %>% 
    mutate(ICC = r_participant_ID/tot_var$total_var[1]) %>% 
    mutate(var = 'individual') %>% 
    rename(est = r_participant_ID)
progs <- mood%>%
    spread_draws(r_program_ID__affenga[condition, term]) %>% 
    group_by(.chain, .iteration) %>% 
    summarize(r_program_ID = var(r_program_ID__affenga)) %>% 
    ungroup() %>% 
    mutate(ICC = r_program_ID/tot_var$total_var[1]) %>% 
    mutate(var = 'program') %>% 
    rename(est = r_program_ID)
dda <- bind_rows(beeps, peeps, progs, resid)
gma <- dda %>% 
    group_by(var) %>% 
    summarize(var_mean = mean(est),
              lower_95_ci = quantile(est, c(.05, .95))[1],
              upper_95_ci = quantile(est, c(.05, .95))[2],
              ICC_mean = mean(ICC),
              lower_95_ci_icc = quantile(ICC, c(.05, .95))[1],
              upper_95_ci_icc = quantile(ICC, c(.05, .95))[2])
# BEH 
resid <- mood %>% 
    spread_draws(sigma_behenga) %>% 
    mutate(est = sigma_behenga ^ 2) %>% 
    mutate(var = "residual") %>% 
    select(-.chain, -sigma_behenga) %>% 
    mutate(ICC = est /tot_var$total_var[1])
beeps <- mood%>%
    spread_draws(r_beep_ID__behenga[condition, term]) %>% 
    group_by(.chain, .iteration) %>% 
    summarize(r_beep_ID = var(r_beep_ID__behenga)) %>% 
    ungroup() %>% 
    mutate(ICC = r_beep_ID/tot_var$total_var[1]) %>% 
    mutate(var = 'situation') %>% 
    rename(est = r_beep_ID)
peeps <- mood %>%
    spread_draws(r_participant_ID__behenga[condition, term]) %>% 
    group_by(.chain, .iteration) %>% 
    summarize(r_participant_ID = var(r_participant_ID__behenga)) %>% 
    ungroup() %>% 
    mutate(ICC = r_participant_ID/tot_var$total_var[1]) %>% 
    mutate(var = 'individual') %>% 
    rename(est = r_participant_ID)
progs <- mood%>%
    spread_draws(r_program_ID__behenga[condition, term]) %>% 
    group_by(.chain, .iteration) %>% 
    summarize(r_program_ID = var(r_program_ID__behenga)) %>% 
    ungroup() %>% 
    mutate(ICC = r_program_ID/tot_var$total_var[1]) %>% 
    mutate(var = 'program') %>% 
    rename(est = r_program_ID)
ddb <- bind_rows(beeps, peeps, progs, resid)
gmb <- ddb %>% 
    group_by(var) %>% 
    summarize(var_mean = mean(est),
              lower_95_ci = quantile(est, c(.05, .95))[1],
              upper_95_ci = quantile(est, c(.05, .95))[2],
              ICC_mean = mean(ICC),
              lower_95_ci_icc = quantile(ICC, c(.05, .95))[1],
              upper_95_ci_icc = quantile(ICC, c(.05, .95))[2])
# COG
resid <- mood %>% 
    spread_draws(sigma_cogenga) %>% 
    mutate(est = sigma_cogenga ^ 2) %>% 
    mutate(var = "residual") %>% 
    select(-.chain, -sigma_cogenga) %>% 
    mutate(ICC = est /tot_var$total_var[1])
beeps <- mood%>%
    spread_draws(r_beep_ID__cogenga[condition, term]) %>% 
    group_by(.chain, .iteration) %>% 
    summarize(r_beep_ID = var(r_beep_ID__cogenga)) %>% 
    ungroup() %>% 
    mutate(ICC = r_beep_ID/tot_var$total_var[1]) %>% 
    mutate(var = 'situation') %>% 
    rename(est = r_beep_ID)
peeps <- mood %>%
    spread_draws(r_participant_ID__cogenga[condition, term]) %>% 
    group_by(.chain, .iteration) %>% 
    summarize(r_participant_ID = var(r_participant_ID__cogenga)) %>% 
    ungroup() %>% 
    mutate(ICC = r_participant_ID/tot_var$total_var[1]) %>% 
    mutate(var = 'individual') %>% 
    rename(est = r_participant_ID)
progs <- mood%>%
    spread_draws(r_program_ID__cogenga[condition, term]) %>% 
    group_by(.chain, .iteration) %>% 
    summarize(r_program_ID = var(r_program_ID__cogenga)) %>% 
    ungroup() %>% 
    mutate(ICC = r_program_ID/tot_var$total_var[1]) %>% 
    mutate(var = 'program') %>% 
    rename(est = r_program_ID)
ddc <- bind_rows(beeps, peeps, progs, resid)
gmc <- ddc %>% 
    group_by(var) %>% 
    summarize(var_mean = mean(est),
              lower_95_ci = quantile(est, c(.05, .95))[1],
              upper_95_ci = quantile(est, c(.05, .95))[2],
              ICC_mean = mean(ICC),
              lower_95_ci_icc = quantile(ICC, c(.05, .95))[1],
              upper_95_ci_icc = quantile(ICC, c(.05, .95))[2])

dda <- dda %>% mutate(out = "affective")
ddb <- ddb %>% mutate(out = "behavioral")
ddc <- ddc %>% mutate(out = "cognitive")

dddd <- dda %>% 
    bind_rows(ddb) %>% 
    bind_rows(ddc) %>% 
    select(-.draw)

dddd <- dddd %>% 
    mutate(outcome = tools::toTitleCase(out)) %>% 
    filter(var!="residual")

gma <- gma %>% mutate(out = "affective")
gmb <- gmb %>% mutate(out = "behavioral")
gmc <- gmc %>% mutate(out = "cognitive")

gmd <- gma %>% 
    bind_rows(gmb) %>% 
    bind_rows(gmc)

gmd <- gmd %>% mutate(outcome = tools::toTitleCase(out),
                      var = tools::toTitleCase(var))

gmd %>% 
    mutate_if(is.numeric, round, 3) %>% 
    mutate(ci = str_c(var_mean, " [", lower_95_ci, ", ", upper_95_ci, "]"),
           ci_ICC = str_c(ICC_mean, " [", lower_95_ci_icc, ", ", upper_95_ci_icc, "]")) %>% 
    select(outcome,var, ci, ci_ICC) %>% 
    clipr::write_clip()

ll <- gmd %>% group_by(outcome) %>% summarize(sum_ICC = sum(ICC))

# gmd %>% 
#     left_join(ll) %>% 
#     mutate(outcome = str_c(outcome, " R^2 =", ))

p <- dddd %>% 
    mutate(outcome = tools::toTitleCase(out),
           var = tools::toTitleCase(var)) %>%
    #filter(var != "Residual") %>% 
    ggplot(aes(x = ICC, fill = var)) + 
    geom_density(alpha = .5) +
    facet_grid(rows = vars(outcome)) +
    geom_vline(aes(xintercept = ICC_mean, color = var), linetype = 4, size = .75, data = gmd) +
    ggrepel::geom_label_repel(aes(
        x = ICC_mean,
        label = str_c(tools::toTitleCase(gmd$var), " ICC = ", round(gmd$ICC_mean, 3)), 
        y = 25),
        data = gmd)

p + 
    theme_bw() +
    # scale_fill_manual(values = c( '#fb8072', '#8dd3c7','#ffffb3')) +
    # scale_color_manual(values = c('#fb8072', '#8dd3c7', '#ffffb3')) +
    scale_fill_brewer(type = "qual", palette = "Set2") +
    scale_color_brewer(type = "qual", palette = "Set2") +
    ylab(NULL) +
    xlab("Intra-class Correlation") +
    theme(legend.position = "none") +
    theme(axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank()) +
    theme(text = element_text(size = 18, family = "Times"))

ggsave("2019-09-25-esm-iccs.png", width = 9, height = 9)
```

# Beep

```{r}
beep_aff_beh <- mood %>% 
    spread_draws(cor_beep_ID__affenga_Intercept__behenga_Intercept) %>% 
    mutate(est = cor_beep_ID__affenga_Intercept__behenga_Intercept ^ 2) %>% 
    mutate(var = "beep_aff_beh") %>% 
    summarize(var = "beep_aff_beh",
              est = mean(est),
              lower_95_ci = quantile(cor_beep_ID__affenga_Intercept__behenga_Intercept, c(.05, .95))[1],
              upper_95_ci = quantile(cor_beep_ID__affenga_Intercept__behenga_Intercept, c(.05, .95))[2])

beep_aff_cog <- mood %>% 
    spread_draws(cor_beep_ID__affenga_Intercept__cogenga_Intercept) %>% 
    mutate(est = cor_beep_ID__affenga_Intercept__cogenga_Intercept ^ 2) %>% 
    mutate(var = "beep_aff_cog") %>% 
    summarize(var = "beep_aff_cog",
              est = mean(est),
              lower_95_ci = quantile(cor_beep_ID__affenga_Intercept__cogenga_Intercept, c(.05, .95))[1],
              upper_95_ci = quantile(cor_beep_ID__affenga_Intercept__cogenga_Intercept, c(.05, .95))[2])

beep_beh_cog <- mood %>% 
    spread_draws(cor_beep_ID__behenga_Intercept__cogenga_Intercept) %>% 
    mutate(est = cor_beep_ID__behenga_Intercept__cogenga_Intercept ^ 2) %>% 
    mutate(var = "beep_beh_cog") %>% 
    summarize(var = "beep_beh_cog",
              est = mean(est),
              lower_95_ci = quantile(cor_beep_ID__behenga_Intercept__cogenga_Intercept, c(.05, .95))[1],
              upper_95_ci = quantile(cor_beep_ID__behenga_Intercept__cogenga_Intercept, c(.05, .95))[2])
```

# Participant

```{r}
participant_aff_beh <- mood %>% 
    spread_draws(cor_participant_ID__affenga_Intercept__behenga_Intercept) %>% 
    mutate(est = cor_participant_ID__affenga_Intercept__behenga_Intercept ^ 2) %>% 
    mutate(var = "participant_aff_beh") %>% 
    summarize(var = "participant_aff_beh",
              est = mean(est),
              lower_95_ci = quantile(cor_participant_ID__affenga_Intercept__behenga_Intercept, c(.05, .95))[1],
              upper_95_ci = quantile(cor_participant_ID__affenga_Intercept__behenga_Intercept, c(.05, .95))[2])

participant_aff_cog <- mood %>% 
    spread_draws(cor_participant_ID__affenga_Intercept__cogenga_Intercept) %>% 
    mutate(est = cor_participant_ID__affenga_Intercept__cogenga_Intercept ^ 2) %>% 
    mutate(var = "participant_aff_cog") %>% 
    summarize(var = "participant_aff_cog",
              est = mean(est),
              lower_95_ci = quantile(cor_participant_ID__affenga_Intercept__cogenga_Intercept, c(.05, .95))[1],
              upper_95_ci = quantile(cor_participant_ID__affenga_Intercept__cogenga_Intercept, c(.05, .95))[2])

participant_beh_cog <- mood %>% 
    spread_draws(cor_participant_ID__behenga_Intercept__cogenga_Intercept) %>% 
    mutate(est = cor_participant_ID__behenga_Intercept__cogenga_Intercept ^ 2) %>% 
    mutate(var = "participant_beh_cog") %>% 
    summarize(var = "participant_beh_cog",
              est = mean(est),
              lower_95_ci = quantile(cor_participant_ID__behenga_Intercept__cogenga_Intercept, c(.05, .95))[1],
              upper_95_ci = quantile(cor_participant_ID__behenga_Intercept__cogenga_Intercept, c(.05, .95))[2])
```


# Program

```{r}
program_aff_beh <- mood %>% 
    spread_draws(cor_program_ID__affenga_Intercept__behenga_Intercept) %>% 
    mutate(est = cor_program_ID__affenga_Intercept__behenga_Intercept ^ 2) %>% 
    mutate(var = "program_aff_beh") %>% 
    summarize(var = "program_aff_beh",
              est = mean(est),
              lower_95_ci = quantile(cor_program_ID__affenga_Intercept__behenga_Intercept, c(.05, .95))[1],
              upper_95_ci = quantile(cor_program_ID__affenga_Intercept__behenga_Intercept, c(.05, .95))[2])

program_aff_cog <- mood %>% 
    spread_draws(cor_program_ID__affenga_Intercept__cogenga_Intercept) %>% 
    mutate(est = cor_program_ID__affenga_Intercept__cogenga_Intercept ^ 2) %>% 
    mutate(var = "program_aff_cog") %>% 
    summarize(var = "program_aff_cog",
              est = mean(est),
              lower_95_ci = quantile(cor_program_ID__affenga_Intercept__cogenga_Intercept, c(.05, .95))[1],
              upper_95_ci = quantile(cor_program_ID__affenga_Intercept__cogenga_Intercept, c(.05, .95))[2])

program_beh_cog <- mood %>% 
    spread_draws(cor_program_ID__behenga_Intercept__cogenga_Intercept) %>% 
    mutate(est = cor_program_ID__behenga_Intercept__cogenga_Intercept ^ 2) %>% 
    mutate(var = "program_beh_cog") %>% 
    summarize(var = "program_beh_cog",
              est = mean(est),
              lower_95_ci = quantile(cor_program_ID__behenga_Intercept__cogenga_Intercept, c(.05, .95))[1],
              upper_95_ci = quantile(cor_program_ID__behenga_Intercept__cogenga_Intercept, c(.05, .95))[2])
```


# Overall

```{r}
aff_beh <- mood %>% 
    spread_draws(rescor__affenga__behenga) %>% 
    mutate(est = rescor__affenga__behenga ^ 2) %>% 
    mutate(var = "aff_beh") %>% 
    summarize(var = "aff_beh",
              est = mean(est),
              lower_95_ci = quantile(rescor__affenga__behenga, c(.05, .95))[1],
              upper_95_ci = quantile(rescor__affenga__behenga, c(.05, .95))[2])

aff_cog <- mood %>% 
    spread_draws(rescor__affenga__cogenga) %>% 
    mutate(est = rescor__affenga__cogenga ^ 2) %>% 
    mutate(var = "aff_cog") %>% 
    summarize(var = "aff_cog",
              est = mean(est),
              lower_95_ci = quantile(rescor__affenga__cogenga, c(.05, .95))[1],
              upper_95_ci = quantile(rescor__affenga__cogenga, c(.05, .95))[2])

beh_cog <- mood %>% 
    spread_draws(rescor__behenga__cogenga) %>% 
    mutate(est = rescor__behenga__cogenga ^ 2) %>% 
    mutate(var = "beh_cog") %>% 
    summarize(var = "beh_cog",
              est = mean(est),
              lower_95_ci = quantile(rescor__behenga__cogenga, c(.05, .95))[1],
              upper_95_ci = quantile(rescor__behenga__cogenga, c(.05, .95))[2])
```

```{r}
bind_rows(beep_aff_beh, beep_aff_cog, beep_beh_cog,
participant_aff_beh, participant_aff_cog, participant_beh_cog,
program_aff_beh, program_aff_cog, program_beh_cog,
aff_beh, aff_cog, beh_cog) %>% 
    mutate_if(is.numeric, sqrt) %>% 
    mutate_if(is.numeric, round, 3) %>% 
    mutate(est_ci = str_c(est, " [", lower_95_ci, ", ", upper_95_ci, "]")) %>% 
    select(var, est_ci) %>% 
    clipr::write_clip()
```


# intercepts

```{r}
aff_imus <- mood %>% 
    spread_draws(b_affenga_datasetimuscle) %>% 
    select(-.chain) %>% 
    summarize(var = "aff_imus",
              est = mean(b_affenga_datasetimuscle),
              lower_95_ci = quantile(b_affenga_datasetimuscle, c(.05, .95))[1],
              upper_95_ci = quantile(b_affenga_datasetimuscle, c(.05, .95))[2])

beh_imus <- mood %>% 
    spread_draws(b_behenga_datasetimuscle) %>% 
    select(-.chain) %>% 
    summarize(var = "beh_imus",
              est = mean(b_behenga_datasetimuscle),
              lower_95_ci = quantile(b_behenga_datasetimuscle, c(.05, .95))[1],
              upper_95_ci = quantile(b_behenga_datasetimuscle, c(.05, .95))[2])

cog_imus <- mood %>% 
    spread_draws(b_cogenga_datasetimuscle) %>% 
    select(-.chain) %>% 
    summarize(var = "cog_imus",
              est = mean(b_cogenga_datasetimuscle),
              lower_95_ci = quantile(b_cogenga_datasetimuscle, c(.05, .95))[1],
              upper_95_ci = quantile(b_cogenga_datasetimuscle, c(.05, .95))[2])


aff_scimo<- mood %>% 
    spread_draws(b_affenga_datasetscimo) %>% 
    select(-.chain) %>% 
    summarize(var = "aff_imus",
              est = mean(b_affenga_datasetscimo),
              lower_95_ci = quantile(b_affenga_datasetscimo, c(.05, .95))[1],
              upper_95_ci = quantile(b_affenga_datasetscimo, c(.05, .95))[2])

beh_scimo<- mood %>% 
    spread_draws(b_behenga_datasetscimo) %>% 
    select(-.chain) %>% 
    summarize(var = "beh_imus",
              est = mean(b_behenga_datasetscimo),
              lower_95_ci = quantile(b_behenga_datasetscimo, c(.05, .95))[1],
              upper_95_ci = quantile(b_behenga_datasetscimo, c(.05, .95))[2])

cog_scimo<- mood %>% 
    spread_draws(b_cogenga_datasetscimo) %>% 
    select(-.chain) %>% 
    summarize(var = "cog_imus",
              est = mean(b_cogenga_datasetscimo),
              lower_95_ci = quantile(b_cogenga_datasetscimo, c(.05, .95))[1],
              upper_95_ci = quantile(b_cogenga_datasetscimo, c(.05, .95))[2])


aff_stemie<- mood %>% 
    spread_draws(b_affenga_datasetstemie) %>% 
    select(-.chain) %>% 
    summarize(var = "aff_imus",
              est = mean(b_affenga_datasetstemie),
              lower_95_ci = quantile(b_affenga_datasetstemie, c(.05, .95))[1],
              upper_95_ci = quantile(b_affenga_datasetstemie, c(.05, .95))[2])

beh_stemie<- mood %>% 
    spread_draws(b_behenga_datasetstemie) %>% 
    select(-.chain) %>% 
    summarize(var = "beh_imus",
              est = mean(b_behenga_datasetstemie),
              lower_95_ci = quantile(b_behenga_datasetstemie, c(.05, .95))[1],
              upper_95_ci = quantile(b_behenga_datasetstemie, c(.05, .95))[2])

cog_stemie<- mood %>% 
    spread_draws(b_cogenga_datasetstemie) %>% 
    select(-.chain) %>% 
    summarize(var = "cog_imus",
              est = mean(b_cogenga_datasetstemie),
              lower_95_ci = quantile(b_cogenga_datasetstemie, c(.05, .95))[1],
              upper_95_ci = quantile(b_cogenga_datasetstemie, c(.05, .95))[2])

bind_rows(aff_imus, beh_imus, cog_imus,
          aff_scimo, beh_scimo, cog_scimo,
          aff_stemie, beh_stemie, cog_stemie) %>% 
    mutate_if(is.numeric, round, 3) %>% 
    mutate(est_ci = str_c(est, " [", lower_95_ci, ", ", upper_95_ci, "]")) %>% 
    select(var, est_ci) %>% 
    clipr::write_clip()
```

